# Generated by Django 4.0.4 on 2022-05-17 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("cpu", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "player1_choice",
                    models.CharField(
                        choices=[
                            ("ROCK", "Rock"),
                            ("PAPER", "Paper"),
                            ("SCISSORS", "Scissors"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "player2_choice",
                    models.CharField(
                        choices=[
                            ("ROCK", "Rock"),
                            ("PAPER", "Paper"),
                            ("SCISSORS", "Scissors"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "player1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player1",
                        to="player.player",
                    ),
                ),
                (
                    "player2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player2",
                        to="player.player",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="winner",
                        to="player.player",
                    ),
                ),
            ],
        ),
    ]
